const defaults={name:'Saya Art & Advertising',address:'Banderdewa, Dist. Lakhimpur, Assam - 784163',phone:'+91 7086718618',email:'',tax:'',gateway:'Razorpay',key:'',secret:''};
const products=[
 {id:1,name:'Classic visiting cards',cat:'Business',price:299,mark:'YOUR\nBRAND',color:'#d3e8de',tag:'BESTSELLER'},
 {id:2,name:'Rounded stickers',cat:'Labels',price:249,mark:'PEEL\n& GO',color:'#f5cf87',tag:'NEW'},
 {id:3,name:'Premium flyers',cat:'Marketing',price:499,mark:'SAY\nHELLO',color:'#f1a88e',tag:''},
 {id:4,name:'Everyday photo mug',cat:'Gifts',price:349,mark:'GOOD\nMORNING',color:'#b9cfed',tag:''},
 {id:5,name:'A5 notebooks',cat:'Stationery',price:299,mark:'BIG\nIDEAS',color:'#d8db9b',tag:'POPULAR'},
 {id:6,name:'Fabric standee',cat:'Marketing',price:1299,mark:'LOOK\nHERE',color:'#c7b4d9',tag:''},
 {id:7,name:'Custom cotton tee',cat:'Apparel',price:499,mark:'MAKE\nNOISE',color:'#e3b9b4',tag:''},
 {id:8,name:'Thank you cards',cat:'Stationery',price:399,mark:'THANK\nYOU',color:'#c1d9d2',tag:''}
];
let cart=JSON.parse(localStorage.getItem('ic_cart')||'[]'), orders=JSON.parse(localStorage.getItem('ic_orders')||'[]'), activeProduct=null, filter='All';
let savedShop=JSON.parse(localStorage.getItem('ic_shop')||'{}');
let shop={...defaults,...savedShop};
if(savedShop.name==='Ink & Craft') shop={...defaults};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const money=n=>'₹'+Number(n).toLocaleString('en-IN');
function save(){localStorage.setItem('ic_cart',JSON.stringify(cart));localStorage.setItem('ic_orders',JSON.stringify(orders));localStorage.setItem('ic_shop',JSON.stringify(shop))}
function applyShop(){document.querySelectorAll('[data-shop-name]').forEach(x=>x.textContent=shop.name);document.querySelectorAll('[data-address]').forEach(x=>x.textContent=shop.address);document.querySelectorAll('[data-shop-phone]').forEach(x=>x.textContent=shop.phone);$('#shopName').value=shop.name;$('#shopAddress').value=shop.address;$('#shopPhone').value=shop.phone;$('#shopEmail').value=shop.email;$('#shopTax').value=shop.tax;$('#gateway').value=shop.gateway;$('#paymentKey').value=shop.key;$('#webhookSecret').value=shop.secret;$('#paymentNotice').textContent=shop.key?`Online payment will open via ${shop.gateway} when deployed with your secure server integration.`:'Payment gateway is in test mode until you add your provider keys in Admin.'}
function renderCategories(){let cats=[...new Set(products.map(p=>p.cat))];$('#categories').innerHTML=cats.map((c,i)=>`<button class="category" data-cat="${c}"><div class="category-visual" style="background:${['#d3e8de','#f5cf87','#f1a88e','#b9cfed','#d8db9b','#c7b4d9'][i%6]}">${['✦','●','↗','♥','▤','▲'][i%6]}</div><b>${c}</b><span> →</span></button>`).join('');$$('.category').forEach(x=>x.onclick=()=>{filter=x.dataset.cat;renderProducts();location.hash='products'})}
function renderProducts(){let cats=['All',...new Set(products.map(p=>p.cat))];$('#filters').innerHTML=cats.map(c=>`<button class="${c===filter?'active':''}" data-filter="${c}">${c}</button>`).join('');$$('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;renderProducts()});let shown=filter==='All'?products:products.filter(p=>p.cat===filter);$('#productGrid').innerHTML=shown.map((p,i)=>`<button class="product" data-id="${p.id}">${p.tag?`<span class="tag">${p.tag}</span>`:''}<div class="product-image" data-mark="${p.mark}" style="background:${p.color};--tilt:${i%2?'-4deg':'4deg'}"></div><h3>${p.name}</h3><p>${p.cat}</p><span class="price">from ${money(p.price)}</span></button>`).join('');$$('.product').forEach(x=>x.onclick=()=>openCustomizer(+x.dataset.id))}
function openModal(id){$('#'+id).classList.add('show');$('#'+id).setAttribute('aria-hidden','false')}function closeModal(id){$('#'+id).classList.remove('show');$('#'+id).setAttribute('aria-hidden','true')}
function openCustomizer(id){activeProduct=products.find(p=>p.id===id);$('#customTitle').textContent=activeProduct.name;$('#customPrice').textContent='from '+money(activeProduct.price);$('#customText').value='';$('#artwork').value='';$('#uploadStatus').textContent='Optional — we will check your file before printing.';preview();openModal('productModal')}
function preview(){if(!activeProduct)return;$('#customPreview').innerHTML=`<div>${($('#customText').value||activeProduct.mark).replace(/\n/g,'<br>')}</div>`}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0), total=cart.reduce((s,x)=>s+x.price*x.qty,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div class="cart-thumbnail">${x.mark||'PRINT'}</div><div><b>${x.name}</b><span>${x.detail} · ${money(x.price)}</span><button class="remove" data-remove="${i}">Remove</button></div></div>`).join(''):'<p style="font-size:13px;color:var(--muted);padding-top:30px">Your bag is ready for a good idea.</p>';$$('[data-remove]').forEach(x=>x.onclick=()=>{cart.splice(+x.dataset.remove,1);save();renderCart()})}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function renderAdmin(){ $('#adminProducts').innerHTML=products.map(p=>`<div class="admin-product"><span><b>${p.name}</b><br>₹ <input data-price="${p.id}" value="${p.price}" type="number"></span><button class="link-button" data-save-price="${p.id}">Save</button></div>`).join('');$$('[data-save-price]').forEach(b=>b.onclick=()=>{let p=products.find(x=>x.id===+b.dataset.savePrice);p.price=+document.querySelector(`[data-price="${p.id}"]`).value;renderProducts();toast('Price updated for this session')});$('#ordersList').innerHTML=orders.length?orders.map(o=>`<div class="order"><b>${o.id} · ${o.name}</b>${o.items} item(s) · ${money(o.total)} · ${o.date}<br><span>${o.status}</span></div>`).join(''):'<p style="font-size:13px;color:var(--muted)">No orders yet. New orders placed in this demo appear here.</p>'}
$('#openCart').onclick=()=>{$('#cartDrawer').classList.add('open');renderCart()};$$('[data-close]').forEach(b=>b.onclick=()=>{let id=b.dataset.close;id==='cartDrawer'?$('#cartDrawer').classList.remove('open'):closeModal(id)});$('#openAdmin').onclick=()=>{renderAdmin();openModal('adminModal')};$('#searchButton').onclick=()=>{openModal('searchModal');setTimeout(()=>$('#searchInput').focus(),10)};
$('#customText').oninput=preview;$('#artwork').onchange=e=>$('#uploadStatus').textContent=e.target.files[0]?`${e.target.files[0].name} ready for review.`:'Optional — we will check your file before printing.';$('#addCustomProduct').onclick=()=>{cart.push({name:activeProduct.name,price:activeProduct.price,qty:1,mark:activeProduct.mark,detail:`${$('#quantity').value} pcs${$('#customText').value?' · '+$('#customText').value:''}`});save();renderCart();closeModal('productModal');toast('Added to your bag')};
$('#checkoutButton').onclick=()=>{if(!cart.length)return toast('Add a product first');$('#cartDrawer').classList.remove('open');openModal('checkoutModal')};$('#checkoutForm').onsubmit=e=>{e.preventDefault();let form=new FormData(e.target),total=cart.reduce((s,x)=>s+x.price*x.qty,0);orders.unshift({id:'#'+Math.floor(100000+Math.random()*899999),name:form.get('')||e.target.querySelector('input').value,items:cart.length,total,date:new Date().toLocaleDateString('en-IN'),status:shop.key?'Payment pending gateway confirmation':'Demo order — payment keys needed'});cart=[];save();renderCart();e.target.reset();closeModal('checkoutModal');toast('Order received — check Admin → Orders')};
$('#profileForm').onsubmit=e=>{e.preventDefault();shop={...shop,name:$('#shopName').value,address:$('#shopAddress').value,phone:$('#shopPhone').value,email:$('#shopEmail').value,tax:$('#shopTax').value};save();applyShop();toast('Shop profile saved')};$('#paymentForm').onsubmit=e=>{e.preventDefault();shop={...shop,gateway:$('#gateway').value,key:$('#paymentKey').value,secret:$('#webhookSecret').value};save();applyShop();toast('Payment settings saved')};
$$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button,.admin-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab+'Panel').classList.add('active');if(b.dataset.tab==='orders')renderAdmin()});$('#searchInput').oninput=e=>{let q=e.target.value.toLowerCase();$('#searchResults').innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)).map(p=>`<button class="search-result link-button" data-result="${p.id}">${p.name} <small>· ${p.cat}</small></button>`).join('')||'<p>No matching products.</p>';$$('[data-result]').forEach(x=>x.onclick=()=>{closeModal('searchModal');openCustomizer(+x.dataset.result)})};$('#browseDeals').onclick=()=>{filter='All';renderProducts();location.hash='products'};$('#viewAll').onclick=()=>{filter='All';renderProducts();location.hash='products'};$('#quoteButton').onclick=()=>toast('Quote request form: add your business contact in Admin before publishing.');$('.modal').addEventListener?.('click',()=>{});$('#year').textContent=new Date().getFullYear();applyShop();renderCategories();renderProducts();renderCart();
